spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/count?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    show-sql: true
    # hibernate Mysql 설정
    database-platform: org.hibernate.dialect.MySQL8Dialect

    # DB의 고유 기능 사용 가능
    hibernate:
      ddl-auto: create
