version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 1005
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: 1005
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   interval: 10s
    #   retries: 5
    #   start_period: 30s

  backend:
    build:
      context: ./backend
    container_name: fastapi_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
